# Generated by Django 3.2.13 on 2023-09-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesILike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('how_often', models.CharField(choices=[('O', 'Once a year'), ('T', 'Twice a year'), ('M', 'Three or more times a year')], max_length=1)),
                ('category', models.CharField(choices=[('O', 'Oscar nominated/winner'), ('T', 'Thrilling'), ('S', 'Serious')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TopMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=70)),
                ('genre', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
